image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - Test
  - Build and Release Images
  - Deploy

# Test:
#   stage: Test
#   before_script:
#   - docker build -t registry.gitlab.com/shogun-courses/multi-k8s/react-test -f ./client/Dockerfile.dev ./client
#   script:
#     - docker run -e CI=true registry.gitlab.com/shogun-courses/multi-k8s/react-test npm test

Build:
  stage: Build and Release Images
  variables:
    REPO_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/multi-client:latest ./client
    - docker build -t $CI_REGISTRY_IMAGE/multi-server:latest ./server
    - docker build -t $CI_REGISTRY_IMAGE/multi-worker:latest ./worker
    - docker push $CI_REGISTRY_IMAGE/multi-client:latest
    - docker push $CI_REGISTRY_IMAGE/multi-server:latest
    - docker push $CI_REGISTRY_IMAGE/multi-worker:latest

Deploy:
  stage: Deploy
  script:
    - kubectl create secret docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run=client | kubectl apply -f
